### ISSUE TITLE
No menu bar on Android TV Os

### ISSUE THREAD

**Issue by function1983** [wolpi/prim-ftpd#154]
I installed it via F-Droid on A95X Pro running stock Android TV Os and there is no menu bar to configure nor start the server.
Screenshot is provided.
[https://i.postimg.cc/bwbnCDvH/IMG_20180921_103453.jpg](url)

Not sure if it's a bug or a feature? :)

**Comment by wolpi** [comment]
This looks a lot like #123 which was solved in version 5.6. What is the version you got from f-droid? Might be that your device reports it would have a touchscreen so buttons are not shown.

**Comment by function1983** [comment]
It was 5.9. To double check, I reinstalled but the problem persists.

<a href="https://postimg.cc/87spknhn" target="_blank"><img src="https://i.postimg.cc/zGFVjs35/IMG_20180924_084320.jpg" alt="IMG_20180924_084320"/></a><br/><br/>
<a href="https://postimg.cc/BtGn5p0X" target="_blank"><img src="https://i.postimg.cc/tRsnjvvt/IMG_20180924_084424.jpg" alt="IMG_20180924_084424"/></a><br/><br/>

**Comment by wolpi** [comment]
That surly means the recognition if current device is a tv does not work reliably and i need to find another way. This will take some time.

**Comment by wolpi** [comment]
Well currently that would cause buttons to be shown on phones, tablets, ... That ist not what I want.

I think there should be another activity class for leanback only. That one would use a dedicated leanback layout which would contain buttons.

Files targeting phones and the like would not contain anything regarding buttons.

**Comment by function1983** [comment]
Hi @wolpi , just to give you an update. I tried it on another box of mine (T95Z Plus) and it works absolutely just fine. So it might be very device or OS specific. I have 2 other android boxes. I might give it a try when I have time. (TX3 mini and Mini M8S Pro/T95N).
Same software version 5.9. Sorry for the dark screenshots, bad phone camera but should do it.

<a href="https://postimg.cc/5jkGF3GN" target="_blank"><img src="https://i.postimg.cc/SNyp31f8/IMG_20181003_194914.jpg" alt="IMG_20181003_194914"/></a><br/><br/>
<a href="https://postimg.cc/Z0q2RgwM" target="_blank"><img src="https://i.postimg.cc/Wpmv9cgT/IMG_20181003_194952.jpg" alt="IMG_20181003_194952"/></a><br/><br/>
<a href="https://postimg.cc/Kk0Wfr8f" target="_blank"><img src="https://i.postimg.cc/C50VFcy3/IMG_20181003_195417.jpg" alt="IMG_20181003_195417"/></a><br/><br/>

**Comment by wolpi** [comment]
As you can see I did some changes for this issue. And I am going to release it soon. Would be great if you could test it on your devices once it's out.
